### ISSUE TITLE
from camera.configs.blackfly_configs  import configs ### no module "camera"?

### ISSUE THREAD

**Issue by LKINSEY** [uutzinger/camera#1]
Hi, trying to find a code that works for my blackfly s cameras, works as in with a frame rate above 300 fps. This code looks promising but when I run the code I get an error with the line of code in the title. I know what file it is referencing but I don't know what to do to wiggle around this error. Any suggestions?

Many Thanks

**Comment by uutzinger** [comment]
the folder "configs" needs to be accessible in the same folder where your main program is located. If you can not get it working you can load the text that is in the configs file and copy it into your main program at the beginning after the imports.
